# Derived from https://github.com/actions/runner-images

name: Bug Report
description: Submit a bug report.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is, and why you consider it to be a bug.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Affected area 
      description: You can mark more than one
      options:
        - label: Front-End
        - label: Back-End
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: A description of what is actually happening.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      placeholder: |
        A description with steps to reproduce the issue.
        1. Step 1
        2. Step 2
    validations:
        required: true
  - type: dropdown
    attributes:
      label: "Priority"
      description: What is this issue priority?
      multiple: false
      options:
        - Low
        - Medium
        - High
        - URGENT!
    validations:
      required: true