name: build-web 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    env:
        ENABLE_PDF_EXPORT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing dep
        run: | 
            npm run installWebDep
      - name: Building Webapp
        run: npm run buildWeb
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: web-build
          FOLDER: ./src/web/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}