name: build-bins 
on:
  workflow_run:
    workflows: ["build-web"]
    types:
      - completed

permissions:
  contents: write
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
      - name: Installing dep
        run: | 
            pip install -r requirements.txt
      - name: Fetching Webapp
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
      - name: Unzip web build
        run: 7z x Web_Bolinho_${{ github.run_number }}.zip -o./src/web/build
      - name: Building Exe
        run: |
            python -m eel src/main.py src/web/build --onefile --name Bolinho --icon ./src/web/build/favicon.ico
      - name: Upload Exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: ./dist/Bolinho.exe

      # - name: Prepare files for release
      #   run: |
      #     xcopy ./src ./Bolinho/ /e /q
      #     mkdir Bolinho\src\web
      #     xcopy ./src/web/build ./Bolinho/src/web/build /e /q
      #     copy ./requirements.txt ./Bolinho/src
      #     zip -r Bolinho_${{ github.run_number }}.zip ./Bolinho/*
      # - name: Build Exe
      #   run: |
      #     python -m eel src/main.py src/web/build --onefile --name Bolinho --icon ./src/web/build/favicon.ico
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: false
      #     title: "Development Build ${{ github.run_number }}"
      #     files: |
      #       ./Bolinho_${{ github.run_number }}.zip
      #       ./Bolinho/dist/Bolinho.exe

