name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    env:
        ENABLE_PDF_EXPORT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Installing dep
        run: pip install -r docs/requirements.txt
      - name: Building
        run: mkdocs gh-deploy --force
      - name: Add files
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout gh-pages
          git checkout ${GITHUB_REF##*/} -- src/web/build/.
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push origin gh-pages
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Installing dep
        run: npm run installDep
      - name: Build binaries
        run: npm run buildBin
      - name: Create Release
        run: |
          cp -r ./src ./Bolinho/
          rm -fr ./Bolinho/src/web
          rm -fr ./Bolinho/src/build
          rm -fr ./Bolinho/src/dist
          rm -fr ./Bolinho/src/__pycache__
          rm -f ./Bolinho/src/.gitignore
          rm -f ./Bolinho/src/*.spec
          mkdir Bolinho/src/web
          cp -r ./src/web/build/ ./Bolinho/src/web/build
          cp requirements.txt ./Bolinho/          
          zip -r Bolinho.zip ./Bolinho/*
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            src/dist/
            ./Bolinho.zip
