name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    env:
        ENABLE_PDF_EXPORT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Installing dep
        run: | 
            npm run installDep
            pip install -r docs/requirements.txt
      - name: Building Webapp
        run: npm run buildWeb
      - name: Building Documentation
        run: |
            mkdocs build
            cp -r ./src/web/build ./site/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./site
      - name: Create Release
        run: |
          cp -r ./src ./Bolinho/
          rm -fr ./Bolinho/src/web
          rm -fr ./Bolinho/src/dist
          rm -fr ./Bolinho/src/__pycache__
          rm -f ./Bolinho/src/.gitignore
          rm -f ./Bolinho/src/*.spec
          mkdir Bolinho/src/web
          cp -r ./src/web/build ./Bolinho/src/web/build
          cp requirements.txt ./Bolinho/          
          zip -r Bolinho.zip ./Bolinho/*
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            ./Bolinho.zip

